from langchain.tools import tool
from typing import Literal
from langchain_core.messages import RemoveMessage
from langgraph.graph.message import REMOVE_ALL_MESSAGES
from enum import Enum

agentic_model = None


class WorkflowStage(Enum):
    INTENT = "intent"
    PHASES = "phases"
    DETAILS = "details"
    SCHEDULING = "scheduling"


def setup_tools(model_instance):
    """Set the global model instance for tools to access"""
    from src.model import AgenticSchedulerModel

    model: AgenticSchedulerModel = model_instance
    global agentic_model
    agentic_model = model


#### Intent Tools ####


@tool
def transition_to_phases(intent_description: str) -> str:
    """
    Call this tool when the user's intent is clear and you are ready to propose phases.

    """
    return f"Intent confirmed: {intent_description}. Moving to Phase Identification."


@tool
def submit_construction_intent(
    project_type: Literal[
        "residential", "commercial", "industrial", "infrastructure", "other"
    ],
    building_category: str,
    size_value: float,
    size_unit: str,
    floors: int | None = None,
    location: str | None = None,
    special_requirements: list[str] | None = None,
    timeline_preference: str | None = None,
    budget_min: float | None = None,
    budget_max: float | None = None,
    budget_currency: str = "USD",
    other_details: dict[str, str] | None = None,
) -> str:
    """
    Submit the finalized construction project intent after gathering all necessary information.

    Only call this tool when you have collected sufficient information about:
    - Project type and category
    - Size with proper units
    - Other relevant details the user has provided
    - Store other detail in other_details. the key should be phases_agent,
    details_agent or scheduling_agent. depedending on who requires that data

    Do NOT call this for initial greetings or when you still need more information.
    """
    return "Intent submitted successfully for user confirmation"


#### Phases Tools ####


@tool
def confirm_phases(phases_list: str) -> list:
    """
    Call this tool when the user agrees to the proposed phases.
    Input should be a comma-separated list of phases (e.g., "Foundation, Framing, Roofing").
    This will also update the phases state in the model.
    """
    # Parse the list
    phases = [p.strip() for p in phases_list.split(",")]
    if not phases:
        return []

    return phases


# @tool
# def complete_current_phase() -> str:
#     """
#     Call this tool when the user is satisfied with the details of the current phase.
#     This will move to the next phase or to the Scheduling stage if all phases are done.
#     """
#     if agentic_model is None:
#         return "Error: Model not initialized"

#     from src.model import WorkflowStage

# agentic_model.current_phase_index += 1

# if agentic_model.current_phase_index < len(agentic_model.phases):
#     next_phase = agentic_model.phases[agentic_model.current_phase_index]
#     return f"Phase completed. Moving to next phase: {next_phase}"
# else:
#     agentic_model.current_stage = WorkflowStage.SCHEDULING
#     return "All phases completed. Moving to Scheduling stage."


# @tool
# def save_tasks(tasks: list) -> str:
#     """
# Save the list of tasks and dependencies generated by the agent for the current phase.
# Input should be a list of task dictionaries with the following structure:
# [
#     {
#         "name": "task name",
#         "duration_days": number,
#         "dependencies": [
#             ["previous_task_name", "relationship_link", "lag_by"]
#         ],
#         "resources": [["required_resoure_name", "amount"]]
#     }
# ]

#     NOTE -
#     1) A task name in dependency SHOULD EXIST in the tasks list if not change name in dependancy to match it. COMPULSORY.
#     2) All numbers must be without quotes
#     """
#     # if (
#     #     agentic_model is None
#     #     or not hasattr(agentic_model, "scheduler")
#     #     or agentic_model.scheduler is None
#     # ):
#     #     return "Error: Model not initialized"

#     try:
#         # Validate structure (basic check)
#         if not isinstance(tasks, list):
#             return "Error: Input must be a list of task dictionaries."

#         # If tasks are passed as a string (which sometimes happens with LLMs), try to parse
#         if isinstance(tasks, str):
#             tasks = json.loads(tasks)

#         # If current_task is empty, initialize it
#         if not agentic_model.current_task:
#             agentic_model.current_task = {"tasks": []}

#         current_tasks_list = agentic_model.current_task.get("tasks", [])

#         # Check for duplicates?
#         existing_names = {t["name"] for t in current_tasks_list}

#         added_count = 0
#         for task in tasks:
#             if task["name"] not in existing_names:
#                 # Ensure dependencies are tuples
#                 if "dependencies" in task:
#                     task["dependencies"] = [
#                         tuple(dep) if isinstance(dep, list) else dep
#                         for dep in task["dependencies"]
#                     ]
#                 current_tasks_list.append(task)
#                 added_count += 1
#             else:
#                 # Update existing?
#                 pass

#         agentic_model.current_task["tasks"] = current_tasks_list

#         return f"✅ Saved {added_count} tasks. Total tasks: {len(current_tasks_list)}"

#     except Exception as e:
#         return f"Error saving tasks: {str(e)}"


intent_tools = [submit_construction_intent]

phase_tools = [confirm_phases]

details_tools = []
